#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 13 12:56:33 2020
Dictionary of variables measured at Cape Verde Observtory and relevent 
information for dataset access, processing and plotting. 
@author: mjr583
"""

CVAO_dict = {
     'O3' : {'variable' : 'O3',   
                 'ceda_url' : 'http://dap.ceda.ac.uk/thredds/dodsC/badc/capeverde/data/cv-tei-o3/2019/ncas-tei-49i-1_cvao_20190101_o3-concentration_v1.nc',
                 'ebas_url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20061002000000.20190425081904.uv_abs.ozone.air.12y.1h.GB12L_CVO_Ozone_Thermo49series.GB12L_Thermo.lev2.nc',
                 'ebas_var_name' : 'ozone_nmol_per_mol_amean',
                 'ceda_var_name' : '',               
                 'longname' : 'ozone',
                 'abbr' : '$O_3$',
                 'unit': 'ppbv',
                 'scale' : '1e9',
                 'yscale' : 'linear',
                 'start_year' : '2006',
                 'merge_name' : 'O3',
                 'GC_name' : 'O3',
                 'GC_molratio' : 1,
                 'instrument' : ''
                },
    'CO' : {'variable' : 'CO',
                'ebas_url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20160101000000.20190425083930.online_crds.carbon_monoxide.air.3y.1h.GB12L_CVO_Picarro_G2401.GB12L_Picarro.lev2.nc',
                'ceda_url' : '',
                'ebas_var_name' : 'carbon_monoxide_amean',
                'ceda_var_name' : '',
                'longname' : 'carbon_monoxide',
                'abbr' : 'CO',
                'unit': 'ppbv',
                'scale' : '1e9',
                'yscale' : 'linear',
                'start_year' : '2006',
                'merge_name' : 'CO',# (ppbV)',
                'GC_name' : 'CO',
                'GC_molratio' : 1,
                'instrument' : ''
                },
    'CH4' : {'variable' : 'CH4',
                'ebas_url' : '',
                'ceda_url' : '',
                'ebas_var_name' : '',
                'ceda_var_name' : '',
                'longname' : 'methane',
                'abbr' : '$CH_4$',
                'unit': 'ppbv',
                'scale' : '1e9',
                'yscale' : 'linear',
                'start_year' : '2006',
                'merge_name' : 'CH4_all',# (ppbV)',
                'GC_name' : 'CH4',
                'GC_molratio' : 1,
                'instrument' : ''
                },
    'CO2' : {'variable' : 'CO2',
                'ebas_url' : '',
                'ceda_url' : '',
                'ebas_var_name' : '',
                'ceda_var_name' : '',
                'longname' : 'carbon dioxide',
                'abbr' : '$CO_2$',
                'unit': 'ppmv',
                'scale' : '1e9',
                'yscale' : 'linear',
                'start_year' : '2006',
                'merge_name' : 'CO2',# (ppmV)',
                'GC_name' : 'CO2',
                'GC_molratio' : 1,
                'instrument' : ''
                },
    'NO' : {'variable' : 'NO',
                'ebas_url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20170101000000.20191024143042.chemiluminescence_photolytic..air.2y.1h.GB12L_CVO_AQD_Nox.GB12L_AQD_NOx.lev2.nc',
                'ceda_url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20170101000000.20191024143042.chemiluminescence_photolytic..air.2y.1h.GB12L_CVO_AQD_Nox.GB12L_AQD_NOx.lev2.nc',                
                'ebas_var_name' : 'nitrogen_monoxide_nmol_per_mol',
                'ceda_var_name' : '',                
                'longname' : 'nitrogen_monoxide',
                'abbr' : 'NO',
                'unit': 'pptv',
                'scale' : '1e9',
                'yscale' : 'log',
                'start_year' : '2006',
                'merge_name' : 'NO',# (pptV)',
                'GC_name' : 'NO',
                'GC_molratio' : 1,
                'instrument' : ''
                },
    'NO2' : {'variable' : 'NO2',
                 'ebas_url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20170101000000.20191024143042.chemiluminescence_photolytic..air.2y.1h.GB12L_CVO_AQD_Nox.GB12L_AQD_NOx.lev2.nc',
                 'ceda_url' : '',
                 'ebas_var_name' : 'nitrogen_dioxide_nmol_per_mol',
                 'ceda_var_name' : '',
                 'longname' : 'nitrogen_dioxide',
                 'abbr' : '$NO_2$',
                 'unit': 'pptv',
                 'scale' : '1e9',
                 'yscale' : 'linear',
                 'start_year' : '2006',
                 'merge_name' : 'NO2',# (pptV)',
                 'GC_name' : 'NO2',
                 'GC_molratio' : 1,
                 'instrument' : ''
                },
    'propane' : {'variable' : 'propane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'propane',
                     'abbr' : '$C_3H_8$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'propane',# (pptV)',
                     'GC_name' : 'C3H8',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'ethane' : {'variable' : 'ethane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'ethane',
                     'abbr' : '$C_2H_6$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'ethane',# (pptV)',
                     'GC_name' : 'C2H6',
                     'GC_molratio' : 2,
                     'instrument' : ''
                },
    'iso_butane' : {'variable' : 'iso_butane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'isobutane',
                     'abbr' : '$HC(CH_3)_3$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'iso_butane',# (;pptV)',
                     'GC_name' : None,    
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'n_butane' : {'variable' : 'n_butane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'nbutane',
                     'abbr' : '$C_4H_{10}$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'n_butane',# (pptV)',
                     'GC_name' : None,    
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'acetylene' : {'variable' : 'acetylene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'acetylene',
                     'abbr' : '$C_2H_2$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'acetylene',# (pptV)',
                     'GC_name' : None,
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'iso_pentane' : {'variable' : 'iso_pentane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'isopentane',
                     'abbr' : '$C_5H_{12}$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'iso_pentane',# (pptV)',
                     'GC_name' : None,
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'n_pentane' : {'variable' : 'n_pentane',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'n_pentane',
                     'abbr' : '$C_5H_{12}$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'n_pentane',# (pptV)',
                     'GC_name' : None,
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'ethene' : {'variable' : 'ethene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'ethene',
                     'abbr' : '$C_2H_4$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'ethene',# (pptV)',
                     'GC_name' : None,
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'propene' : {'variable' : 'propene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'propene',
                     'abbr' : '$C_3H_6$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'propene',# (pptV)',
                     'GC_name' : 'PRPE',
                     'GC_molratio' : 3,
                     'instrument' : ''
                },
    'benzene' : {'variable' : 'benzene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'benzene',
                     'abbr' : '$C_6H_6$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'benzene',# (pptV)',
                     'GC_name' : 'BENZ',
                     'GC_molratio' : 6,
                     'instrument' : ''
                },
    'toluene' : {'variable' : 'toluene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'toluene',
                     'abbr' : '$C_6H_5CH_3$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'toluene',# (pptV)',
                     'GC_name' : 'TOLU',
                     'GC_molratio' : 7,
                     'instrument' : ''
                },
    'Mercury' : {'variable' : 'Mercury',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Mercury',
                     'abbr' : 'T.G. Hg',
                     'unit': 'ngm-3',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'Total Gaseous Mercury (ngm-3)',
                     'GC_name' : None,
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'CHBr3' : {'variable' : 'CHBr3',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Bromoform',
                     'abbr' : '$CHBr_3$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'CHBr3',# (pptV)',
                     'GC_name' : 'CHBr3',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'CH2Br2' : {'variable' : 'CH2Br2',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Dibromomethane',
                     'abbr' : '$CH_2Br_2$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'CH2Br2',# (pptV)',
                     'GC_name' : 'CH2Br2',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'CCl4' : {'variable' : 'CCl4',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Carbon Tetrachloride',
                     'abbr' : '$CCl_4$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'CCl4',# (pptV)',
                     'GC_name' : 'CCl4',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'CH2I2' : {'variable' : 'CH2I2',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Diiodomethane',
                     'abbr' : '$CH_2I_2$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'CH2I2',# (pptV)',
                     'GC_name' : 'CH2I2',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'CH3I' : {'variable' : 'CH3I',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Methyl Iodide',
                     'abbr' : '$CH_3I$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'CH3I',# (pptV)',
                     'GC_name' : 'CH3I',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'CH2ICl' : {'variable' : 'CH2ICl',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Chloroiodomethane',
                     'abbr' : '$CH_2ICl$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'CH2ICl',# (pptV)',
                     'GC_name' : 'CH2ICl',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'CHCl3' : {'variable' : 'CHCl3',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Chloroform',
                     'abbr' : '$CHCl_3$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'CHCl3',# (pptV)',
                     'GC_name' : 'CHCl3',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'CH2BrCl' : {'variable' : 'CH2BrCl',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Bromochloromethane',
                     'abbr' : '$CH_2BrCl$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'CH2BrCl',# (pptV)',
                     'GC_name' : None,
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'CH2IBr' : {'variable' : 'CH2IBr',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Bromoiodomethane',
                     'abbr' : '$CH_2IBr$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'CH2IBr',# (pptV)',
                     'GC_name' : 'CL2IBr',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'CHBr2Cl' : {'variable' : 'CHBr2Cl',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Dibromochloromethane',
                     'abbr' : '$CHBr_2Cl$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'CHBr2Cl',# (pptV)',
                     'GC_name' : None,
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'SO2' : {'variable' : 'SO2',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Sulphur dioxide',
                     'abbr' : '$SO_2$',
                     'unit': 'ppbv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'SO2',# (ppbV)',
                     'GC_name' : 'SO2',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'DMS' : {'variable' : 'DMS',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Dimethyl sulphide',
                     'abbr' : 'DMS',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log', # query
                     'start_year' : '2006',
                     'merge_name' : 'DMS',# (pptV)',
                     'instrument' : ''
                },
    'isoprene' : {'variable' : 'isoprene',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Isoprene',
                     'abbr' : 'Isoprene',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'linear',
                     'start_year' : '2006',
                     'merge_name' : 'Isoprene',# (pptV)',
                     'GC_name' : 'ISOP',
                     'GC_molratio' : 5,
                     'instrument' : ''
                },
    'acetaldehyde' : {'variable' : 'acetaldehyde',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Acetaldehyde',
                     'abbr' : '$C_2H_4O$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'acetaldehyde',
                     'GC_name' : 'ALD2',
                     'GC_molratio' : 2,
                     'instrument' : ''
                },
    'meoh' : {'variable' : 'meoh',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Methanol',
                     'abbr' : '$CH_3OH$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'meoh',
                     'GC_name' : 'MOH',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    'acetone' : {'variable' : 'acetone',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Acetone',
                     'abbr' : '$(CH_3)_2CO$',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'yscale' : 'log',
                     'start_year' : '2006',
                     'merge_name' : 'acetone',
                     'GC_name' : 'ACET',
                     'GC_molratio' : 3,
                     'instrument' : ''
                },
     'Cly' : {'variable' : 'Cly',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Chlorines',
                     'abbr' : '$Cl_y$',
                     'unit': 'ppbv',
                     'scale' : '1e9',
                     'merge_name' : False,
                     'GC_name' : None,
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
     'Bry' : {'variable' : 'Bry',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Bromines',
                     'abbr' : '$Br_y$',
                     'unit': 'ppbv',
                     'scale' : '1e9',
                     'merge_name' : False,
                     'GC_name' : None,
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
     'Iy' : {'variable' : 'Iy',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Iodines',
                     'abbr' : '$I_y$',
                     'unit': 'ppbv',
                     'scale' : '1e9',
                     'merge_name' : False,
                     'GC_name' : None,
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
    }

GC_dict = {
     'HNO3' : {'variable' : 'HNO3',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Nitric Acid',
                     'abbr' : '$HNO_3$',
                     'unit': 'ppbv',
                     'scale' : '1e9',
                     'merge_name' : False,
                     'GC_name' : 'HNO3',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
     'HCl' : {'variable' : 'HCl',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Hydrochloric Acid',
                     'abbr' : 'HCl',
                     'unit': 'ppbv',
                     'scale' : '1e9',
                     'merge_name' : False,
                     'GC_name' : 'HCl',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
     'ClO' : {'variable' : 'ClO',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Chlorine Monoxide',
                     'abbr' : 'ClO',
                     'unit': 'ppbv',
                     'scale' : '1e9',
                     'merge_name' : False,
                     'GC_name' : 'ClO',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
     'IO' : {'variable' : 'IO',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Iodine Monoxide',
                     'abbr' : 'IO',
                     'unit': 'pptv',
                     'scale' : '1e12',
                     'merge_name' : False,
                     'GC_name' : 'IO',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
     'BrO' : {'variable' : 'BrO',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Bromine Oxide',
                     'abbr' : 'BrO',
                     'unit': 'ppbv',
                     'scale' : '1e9',
                     'merge_name' : False,
                     'GC_name' : 'BrO',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },
     'Cly' : {'variable' : 'Cly',
                     'ebas_url': '',
                     'ceda_url' : '',
                     'ebas_var_name' : '',
                     'ceda_var_name' : '',
                     'longname' : 'Chlorines',
                     'abbr' : '$Cl_y$',
                     'unit': 'ppbv',
                     'scale' : '1e9',
                     'merge_name' : False,
                     'GC_name' : 'Cly',
                     'GC_molratio' : 1,
                     'instrument' : ''
                },

    }

'''
    'NOx' : {'url' : 'http://thredds.nilu.no/thredds/dodsC/ebas/CV0001G.20170101000000.20191024143042.chemiluminescence_photolytic..air.2y.1h.GB12L_CVO_AQD_Nox.GB12L_AQD_NOx.lev2.nc',
                'variable' : 'NOx',
                'longname' : 'nitrogen_oxides',
                'abbr' : '$NO_x$',
                'unit': 'ppbv',
                'scale' : '1e9',
                'start_year' : '2006',
                'var_name_a' : 'nitrogen_monoxide_nmol_per_mol',
                'var_name_b' : 'nitrogen_dioxide_nmol_per_mol'
                },
     }
'''
